workspace(name = "cross_language_test")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Needed by com_github_grpc_grpc; Matches
# https://github.com/grpc/grpc/blob/v1.70.1/bazel/grpc_deps.bzl#L58
http_archive(
    name = "com_google_protobuf",
    patch_args = ["-p1"],
    patches = [
        "@com_github_grpc_grpc//third_party:protobuf.patch",
    ],
    sha256 = "cf2db029202bb8eb1471b9bae387cc475d15d9e99c547e6906155033f81249a5",
    strip_prefix = "protobuf-2d4414f384dc499af113b5991ce3eaa9df6dd931",
    urls = [
        # https://github.com/protocolbuffers/protobuf/commits/v29.0
        "https://storage.googleapis.com/grpc-bazel-mirror/github.com/protocolbuffers/protobuf/archive/2d4414f384dc499af113b5991ce3eaa9df6dd931.tar.gz",
        "https://github.com/protocolbuffers/protobuf/archive/2d4414f384dc499af113b5991ce3eaa9df6dd931.tar.gz",
    ],
)

http_archive(
    name = "com_github_grpc_grpc",
    sha256 = "cb4916497ccb948780317d7b345e0cfc6752966f3fde61333976479a8910686b",
    strip_prefix = "grpc-1.70.1",
    urls = ["https://github.com/grpc/grpc/archive/refs/tags/v1.70.1.zip"],
)

http_archive(
    name = "rules_proto_grpc",
    sha256 = "2a0860a336ae836b54671cbbe0710eec17c64ef70c4c5a88ccfd47ea6e3739bd",
    strip_prefix = "rules_proto_grpc-4.6.0",
    urls = ["https://github.com/rules-proto-grpc/rules_proto_grpc/releases/download/4.6.0/rules_proto_grpc-4.6.0.tar.gz"],
)

local_repository(
    name = "tink_cc",
    path = "../../tink_cc",
)

local_repository(
    name = "tink_py",
    path = "../../tink_py",
)

load("@tink_py//:tink_py_deps.bzl", "tink_py_deps")

tink_py_deps()

load("@pybind11_bazel//:python_configure.bzl", "python_configure")
load("@rules_python//python:repositories.bzl", "py_repositories", "python_register_toolchains")

py_repositories()

python_register_toolchains(
    name = "python_3_12",
    ignore_root_user_error = True,
    python_version = "3.12",
)

load("@tink_cc//:tink_cc_deps.bzl", "tink_cc_deps")

tink_cc_deps()

load("@tink_cc//:tink_cc_deps_init.bzl", "tink_cc_deps_init")

tink_cc_deps_init()

load("@rules_python//python:pip.bzl", "pip_parse")

pip_parse(
    name = "tink_py_pip_deps",
    quiet = False,
    requirements_lock = "@tink_py//:requirements_all.txt",
)

# Use `which python3` by default [1] unless PYTHON_BIN_PATH is specified [2].
#
# [1] https://github.com/pybind/pybind11_bazel/blob/fc56ce8a8b51e3dd941139d329b63ccfea1d304b/python_configure.bzl#L434
# [2] https://github.com/pybind/pybind11_bazel/blob/fc56ce8a8b51e3dd941139d329b63ccfea1d304b/python_configure.bzl#L162
python_configure(
    name = "local_config_python",
    python_version = "3",
)

load("@tink_py_pip_deps//:requirements.bzl", tink_py_install_pypi_deps = "install_deps")

tink_py_install_pypi_deps()

# gRPC.

load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")

grpc_deps()

load("@com_github_grpc_grpc//bazel:grpc_extra_deps.bzl", "grpc_extra_deps")

grpc_extra_deps()

# Rules Proto gRPC.

load("@rules_proto_grpc//:repositories.bzl", "rules_proto_grpc_repos", "rules_proto_grpc_toolchains")

rules_proto_grpc_toolchains()

rules_proto_grpc_repos()

load("@rules_proto//proto:repositories.bzl", "rules_proto_dependencies")

rules_proto_dependencies()

load("@rules_proto_grpc//cpp:repositories.bzl", rules_proto_grpc_cpp_repos = "cpp_repos")

rules_proto_grpc_cpp_repos()

load("@rules_proto_grpc//python:repositories.bzl", rules_proto_grpc_python_repos = "python_repos")

rules_proto_grpc_python_repos()

pip_parse(
    name = "rules_proto_grpc_py3_deps",
    python_interpreter = "python3",
    requirements_lock = "@rules_proto_grpc//python:requirements.txt",
)

load("@rules_proto_grpc_py3_deps//:requirements.bzl", "install_deps")

install_deps()

pip_parse(
    name = "pip_deps",
    requirements_lock = "//:requirements.txt",
)

load("@pip_deps//:requirements.bzl", testing_server_deps_install = "install_deps")

testing_server_deps_install()

http_archive(
    name = "org_python_pypi_portpicker",
    build_file = "portpicker.BUILD.bazel",
    sha256 = "c55683ad725f5c00a41bc7db0225223e8be024b1fa564d039ed3390e4fd48fb3",
    strip_prefix = "portpicker-1.5.2/src",
    urls = [
        "https://files.pythonhosted.org/packages/3b/34/bfbd5236c7726452080a92a9f6ea9770cd65f51b05cef319ccb767ed32bf/portpicker-1.5.2.tar.gz",
    ],
)
