workspace(name = "cross_language_test")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Needed by com_github_grpc_grpc; Matches
# https://github.com/grpc/grpc/blob/v1.59.3/bazel/grpc_deps.bzl#L384.
http_archive(
    name = "upb",
    sha256 = "5147e0ab6a28421d1e49004f4a205d84f06b924585e15eaa884cfe13289165b7",
    strip_prefix = "upb-42cd08932e364a4cde35033b73f15c30250d7c2e",
    urls = [
        # https://github.com/protocolbuffers/upb/commits/24.x
        "https://storage.googleapis.com/grpc-bazel-mirror/github.com/protocolbuffers/upb/archive/42cd08932e364a4cde35033b73f15c30250d7c2e.tar.gz",
        "https://github.com/protocolbuffers/upb/archive/42cd08932e364a4cde35033b73f15c30250d7c2e.tar.gz",
    ],
)

# Needed by com_github_grpc_grpc; Matches
# https://github.com/grpc/grpc/blob/v1.65.5/bazel/grpc_deps.bzl#L58
http_archive(
    name = "com_google_protobuf",
    sha256 = "387478260190c540388839a3449c635a69708d92fc38ea6e2364b1196db90ea5",
    strip_prefix = "protobuf-2434ef2adf0c74149b9d547ac5fb545a1ff8b6b5",
    urls = [
        # https://github.com/protocolbuffers/protobuf/commits/v26.1
        "https://storage.googleapis.com/grpc-bazel-mirror/github.com/protocolbuffers/protobuf/archive/2434ef2adf0c74149b9d547ac5fb545a1ff8b6b5.tar.gz",
        "https://github.com/protocolbuffers/protobuf/archive/2434ef2adf0c74149b9d547ac5fb545a1ff8b6b5.tar.gz",
    ],
    patches = [
        "@com_github_grpc_grpc//third_party:protobuf.patch",
        "@com_github_grpc_grpc//third_party:protobuf.10007.patch",
    ],
    patch_args = ["-p1"],
)

http_archive(
    name = "com_github_grpc_grpc",
    sha256 = "14f301f9a6c295f2d3fdae4704182721097a996fb2211d05213096321fc572ac",
    strip_prefix = "grpc-1.65.5",
    urls = ["https://github.com/grpc/grpc/archive/refs/tags/v1.65.5.zip"],
)

http_archive(
    name = "rules_proto_grpc",
    sha256 = "2046e520077f77a87f82cf9bf28cf08a95198a0ef68bd3ce540f657a6b6808da",
    strip_prefix = "rules_proto_grpc-4.5.0",
    urls = ["https://github.com/rules-proto-grpc/rules_proto_grpc/archive/refs/tags/4.5.0.zip"],
)

local_repository(
    name = "tink_cc",
    path = "../../tink_cc",
)

local_repository(
    name = "tink_py",
    path = "../../tink_py",
)

load("@tink_py//:tink_py_deps.bzl", "tink_py_deps")

tink_py_deps()

load("@rules_python//python:repositories.bzl", "py_repositories")

py_repositories()

load("@tink_py//:tink_py_deps_init.bzl", "tink_py_deps_init")

tink_py_deps_init("tink_py")

load("@tink_py_pip_deps//:requirements.bzl", tink_py_install_pypi_deps = "install_deps")

tink_py_install_pypi_deps()

# gRPC.

load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")

grpc_deps()

load("@com_github_grpc_grpc//bazel:grpc_extra_deps.bzl", "grpc_extra_deps")

grpc_extra_deps()

# Rules Proto gRPC.

load("@rules_proto_grpc//:repositories.bzl", "rules_proto_grpc_repos", "rules_proto_grpc_toolchains")

rules_proto_grpc_toolchains()

rules_proto_grpc_repos()

load("@rules_proto//proto:repositories.bzl", "rules_proto_dependencies", "rules_proto_toolchains")

rules_proto_dependencies()

rules_proto_toolchains()

load("@rules_proto_grpc//cpp:repositories.bzl", rules_proto_grpc_cpp_repos = "cpp_repos")

rules_proto_grpc_cpp_repos()

load("@rules_proto_grpc//python:repositories.bzl", rules_proto_grpc_python_repos = "python_repos")

rules_proto_grpc_python_repos()

load("@rules_python//python:pip.bzl", "pip_parse")

pip_parse(
    name = "rules_proto_grpc_py3_deps",
    python_interpreter = "python3",
    requirements_lock = "@rules_proto_grpc//python:requirements.txt",
)

load("@rules_proto_grpc_py3_deps//:requirements.bzl", "install_deps")

install_deps()

pip_parse(
    name = "pip_deps",
    requirements_lock = "//:requirements.txt",
)

load("@pip_deps//:requirements.bzl", testing_server_deps_install = "install_deps")

testing_server_deps_install()

http_archive(
    name = "org_python_pypi_portpicker",
    build_file = "portpicker.BUILD.bazel",
    sha256 = "c55683ad725f5c00a41bc7db0225223e8be024b1fa564d039ed3390e4fd48fb3",
    strip_prefix = "portpicker-1.5.2/src",
    urls = [
        "https://files.pythonhosted.org/packages/3b/34/bfbd5236c7726452080a92a9f6ea9770cd65f51b05cef319ccb767ed32bf/portpicker-1.5.2.tar.gz",
    ],
)
