workspace(name = "testing_cc")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Needed by com_github_grpc_grpc; Matches
# https://github.com/grpc/grpc/blob/v1.65.5/bazel/grpc_deps.bzl#L58
http_archive(
    name = "com_google_protobuf",
    sha256 = "387478260190c540388839a3449c635a69708d92fc38ea6e2364b1196db90ea5",
    strip_prefix = "protobuf-2434ef2adf0c74149b9d547ac5fb545a1ff8b6b5",
    urls = [
        # https://github.com/protocolbuffers/protobuf/commits/v26.1
        "https://storage.googleapis.com/grpc-bazel-mirror/github.com/protocolbuffers/protobuf/archive/2434ef2adf0c74149b9d547ac5fb545a1ff8b6b5.tar.gz",
        "https://github.com/protocolbuffers/protobuf/archive/2434ef2adf0c74149b9d547ac5fb545a1ff8b6b5.tar.gz",
    ],
    patches = [
        "@com_github_grpc_grpc//third_party:protobuf.patch",
        "@com_github_grpc_grpc//third_party:protobuf.10007.patch",
    ],
    patch_args = ["-p1"],
)

local_repository(
    name = "tink_cc",
    path = "../../tink_cc",
)

local_repository(
    name = "tink_cc_gcpkms",
    path = "../../tink_cc_gcpkms",
)

local_repository(
    name = "tink_cc_awskms",
    path = "../../tink_cc_awskms",
)

load("@tink_cc_gcpkms//:tink_cc_gcpkms_deps.bzl", "tink_cc_gcpkms_deps")

tink_cc_gcpkms_deps()

load("@tink_cc//:tink_cc_deps.bzl", "tink_cc_deps")

tink_cc_deps()

load("@tink_cc_gcpkms//:tink_cc_gcpkms_deps_init.bzl", "tink_cc_gcpkms_deps_init")

tink_cc_gcpkms_deps_init()

load("@tink_cc_awskms//:tink_cc_awskms_deps.bzl", "tink_cc_awskms_deps")

tink_cc_awskms_deps()

# Release from 2023-09-12.
http_archive(
    name = "rules_proto_grpc",
    sha256 = "9ba7299c5eb6ec45b6b9a0ceb9916d0ab96789ac8218269322f0124c0c0d24e2",
    strip_prefix = "rules_proto_grpc-4.5.0",
    urls = ["https://github.com/rules-proto-grpc/rules_proto_grpc/releases/download/4.5.0/rules_proto_grpc-4.5.0.tar.gz"],
)

load("@rules_proto_grpc//:repositories.bzl", "rules_proto_grpc_repos", "rules_proto_grpc_toolchains")

rules_proto_grpc_toolchains()

rules_proto_grpc_repos()

load("@rules_proto_grpc//cpp:repositories.bzl", rules_proto_grpc_cpp_repos = "cpp_repos")

rules_proto_grpc_cpp_repos()

load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")

grpc_deps()
